const actionTypes = {
  ANSWER_TRUE: 'ANSWER_TRUE',
  ANSWER_FALSE: 'ANSWER_FALSE',
  HANDLE_ERROR_IN_RANDOM: 'HANDLE_ERROR_IN_RANDOM',
  HANDLE_ERROR_IN_DETAILS: 'HANDLE_ERROR_IN_DETAILS',
  FETCH_RANDOM_SOUND: 'FETCH_RANDOM_SOUND',
  FETCH_DETAILS_SOUND: 'FETCH_DETAILS_SOUND',
  NEXT_LEVEL: 'NEXT_LEVEL',
  RESTORE_ANSWERS: 'RESTORE_ANSWERS',
  UPDATE_RANDOM_SOUND: 'UPDATE_RANDOM_SOUND',
  UPDATE_SELECTED_ANSWER: 'UPDATE_SELECTED_ANSWER',
};

export default actionTypes;
