const actionTypes = {
  ANSWER_TRUE: 'ANSWER_TRUE',
  ANSWER_FALSE: 'ANSWER_FALSE',
  HANDLE_ERROR: 'HANDLE_ERROR',
  FETCH_RANDOM_SOUND: 'FETCH_RANDOM_SOUND',
  FETCH_DETAILS_SOUND: 'FETCH_DETAILS_SOUND',
};

export default actionTypes;
